# Generated by Django 3.2.16 on 2023-10-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco_programs', '0002_auto_20231029_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unescoprogram',
            options={'permissions': [('can_add_program', 'Can add program'), ('can_edit_program', 'Can edit program')]},
        ),
    ]
