# Generated by Django 3.2.16 on 2023-11-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco_programs', '0003_alter_unescoprogram_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unescoprogram',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='Description of the program', max_length=2000, null=True),
        ),
    ]
