# Generated by Django 3.2.16 on 2024-02-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco_programs', '0004_alter_unescoprogram_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='unescoprogram',
            name='logo_image',
            field=models.ImageField(default='program_logos/default.png', help_text='Logo of the program', upload_to='program_logos/'),
        ),
    ]
