# Generated by Django 3.2.16 on 2024-02-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco_programs', '0005_unescoprogram_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unescoprogram',
            name='website',
            field=models.URLField(blank=True, default=None, help_text='Website of the program', null=True),
        ),
    ]
